# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.2
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrest_python.models.v0042_job import V0042Job

class TestV0042Job(unittest.TestCase):
    """V0042Job unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0042Job:
        """Test V0042Job
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0042Job`
        """
        model = V0042Job()
        if include_optional:
            return V0042Job(
                account = '',
                comment = slurmrest_python.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_comment.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_comment(
                    administrator = '', 
                    job = '', 
                    system = '', ),
                allocation_nodes = 56,
                array = slurmrest_python.models.v0_0_42_job_array.v0_0_42_job_array(
                    job_id = 56, 
                    limits = slurmrest_python.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_limits.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_limits(
                        max = slurmrest_python.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_limits_max.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_limits_max(
                            running = slurmrest_python.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_limits_max_running.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_limits_max_running(
                                tasks = 56, ), ), ), 
                    task_id = slurmrest_python.models.v0/0/42_uint32_no_val_struct.v0.0.42_uint32_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    task = '', ),
                association = slurmrest_python.models.v0/0/42_assoc_short.v0.0.42_assoc_short(
                    account = '', 
                    cluster = '', 
                    partition = '', 
                    user = '', 
                    id = 56, ),
                block = '',
                cluster = '',
                constraints = '',
                container = '',
                derived_exit_code = slurmrest_python.models.v0/0/42_process_exit_code_verbose.v0.0.42_process_exit_code_verbose(
                    status = [
                        'INVALID'
                        ], 
                    return_code = slurmrest_python.models.v0/0/42_uint32_no_val_struct.v0.0.42_uint32_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    signal = slurmrest_python.models.v0_0_42_process_exit_code_verbose_signal.v0_0_42_process_exit_code_verbose_signal(
                        id = slurmrest_python.models.v0/0/42_uint16_no_val_struct.v0.0.42_uint16_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        name = '', ), ),
                time = slurmrest_python.models.v0_0_42_job_time.v0_0_42_job_time(
                    elapsed = 56, 
                    eligible = 56, 
                    end = 56, 
                    planned = slurmrest_python.models.v0/0/42_uint64_no_val_struct.v0.0.42_uint64_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    start = 56, 
                    submission = 56, 
                    suspended = 56, 
                    system = slurmrest_python.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_time_system.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_time_system(
                        seconds = 56, 
                        microseconds = 56, ), 
                    limit = slurmrest_python.models.v0/0/42_uint32_no_val_struct.v0.0.42_uint32_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    total = slurmrest_python.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_time_total.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_time_total(
                        seconds = 56, 
                        microseconds = 56, ), 
                    user = slurmrest_python.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_time_user.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_time_user(
                        seconds = 56, 
                        microseconds = 56, ), ),
                exit_code = slurmrest_python.models.v0/0/42_process_exit_code_verbose.v0.0.42_process_exit_code_verbose(
                    status = [
                        'INVALID'
                        ], 
                    return_code = slurmrest_python.models.v0/0/42_uint32_no_val_struct.v0.0.42_uint32_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    signal = slurmrest_python.models.v0_0_42_process_exit_code_verbose_signal.v0_0_42_process_exit_code_verbose_signal(
                        id = slurmrest_python.models.v0/0/42_uint16_no_val_struct.v0.0.42_uint16_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        name = '', ), ),
                extra = '',
                failed_node = '',
                flags = [
                    'NONE'
                    ],
                group = '',
                het = slurmrest_python.models.v0_0_42_job_het.v0_0_42_job_het(
                    job_id = 56, 
                    job_offset = slurmrest_python.models.v0/0/42_uint32_no_val_struct.v0.0.42_uint32_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), ),
                job_id = 56,
                name = '',
                licenses = '',
                mcs = slurmrest_python.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_mcs.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_mcs(
                    label = '', ),
                nodes = '',
                partition = '',
                hold = True,
                priority = slurmrest_python.models.v0/0/42_uint32_no_val_struct.v0.0.42_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                qos = '',
                qosreq = '',
                required = slurmrest_python.models.v0_0_42_job_required.v0_0_42_job_required(
                    cpus = 56, 
                    memory_per_cpu = slurmrest_python.models.v0/0/42_uint64_no_val_struct.v0.0.42_uint64_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    memory_per_node = slurmrest_python.models.v0/0/42_uint64_no_val_struct.v0.0.42_uint64_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), ),
                kill_request_user = '',
                restart_cnt = 56,
                reservation = slurmrest_python.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_reservation.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_reservation(
                    id = 56, 
                    name = '', ),
                script = '',
                stdin_expanded = '',
                stdout_expanded = '',
                stderr_expanded = '',
                stdout = '',
                stderr = '',
                stdin = '',
                state = slurmrest_python.models.v0_0_42_job_state.v0_0_42_job_state(
                    current = [
                        'PENDING'
                        ], 
                    reason = '', ),
                steps = [
                    slurmrest_python.models.v0/0/42_step.v0.0.42_step(
                        time = slurmrest_python.models.v0_0_42_step_time.v0_0_42_step_time(
                            elapsed = 56, 
                            end = slurmrest_python.models.v0/0/42_uint64_no_val_struct.v0.0.42_uint64_no_val_struct(
                                set = True, 
                                infinite = True, 
                                number = 56, ), 
                            start = slurmrest_python.models.v0/0/42_uint64_no_val_struct.v0.0.42_uint64_no_val_struct(
                                set = True, 
                                infinite = True, 
                                number = 56, ), 
                            suspended = 56, 
                            system = slurmrest_python.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_system.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_system(
                                seconds = 56, 
                                microseconds = 56, ), 
                            total = slurmrest_python.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_total.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_total(
                                seconds = 56, 
                                microseconds = 56, ), 
                            user = slurmrest_python.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_user.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_user(
                                seconds = 56, 
                                microseconds = 56, ), ), 
                        exit_code = slurmrest_python.models.v0/0/42_process_exit_code_verbose.v0.0.42_process_exit_code_verbose(
                            status = [
                                'INVALID'
                                ], 
                            return_code = slurmrest_python.models.v0/0/42_uint32_no_val_struct.v0.0.42_uint32_no_val_struct(
                                set = True, 
                                infinite = True, 
                                number = 56, ), 
                            signal = slurmrest_python.models.v0_0_42_process_exit_code_verbose_signal.v0_0_42_process_exit_code_verbose_signal(
                                id = slurmrest_python.models.v0/0/42_uint16_no_val_struct.v0.0.42_uint16_no_val_struct(
                                    set = True, 
                                    infinite = True, 
                                    number = 56, ), 
                                name = '', ), ), 
                        nodes = slurmrest_python.models.v0_0_42_step_nodes.v0_0_42_step_nodes(
                            count = 56, 
                            range = '', 
                            list = [
                                ''
                                ], ), 
                        tasks = slurmrest_python.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tasks.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tasks(
                            count = 56, ), 
                        pid = '', 
                        cpu = slurmrest_python.models.v0_0_42_step_cpu.v0_0_42_step_CPU(
                            requested_frequency = slurmrest_python.models.v0_0_42_step_cpu_requested_frequency.v0_0_42_step_CPU_requested_frequency(
                                min = slurmrest_python.models.v0/0/42_uint32_no_val_struct.v0.0.42_uint32_no_val_struct(
                                    set = True, 
                                    infinite = True, 
                                    number = 56, ), 
                                max = , ), 
                            governor = '', ), 
                        kill_request_user = '', 
                        state = [
                            'PENDING'
                            ], 
                        statistics = slurmrest_python.models.v0_0_42_step_statistics.v0_0_42_step_statistics(
                            energy = slurmrest_python.models.v0_0_42_step_statistics_energy.v0_0_42_step_statistics_energy(
                                consumed = , ), ), 
                        step = slurmrest_python.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_step.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_step(
                            name = '', ), 
                        task = slurmrest_python.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_task.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_task(
                            distribution = '', ), 
                        tres = slurmrest_python.models.v0_0_42_step_tres.v0_0_42_step_tres(
                            requested = slurmrest_python.models.v0_0_42_step_tres_requested.v0_0_42_step_tres_requested(
                                average = [
                                    slurmrest_python.models.v0/0/42_tres.v0.0.42_tres(
                                        type = '', 
                                        name = '', 
                                        count = 56, )
                                    ], ), 
                            allocated = [
                                slurmrest_python.models.v0/0/42_tres.v0.0.42_tres(
                                    type = '', 
                                    name = '', 
                                    count = 56, )
                                ], ), )
                    ],
                submit_line = '',
                tres = slurmrest_python.models.v0_0_42_job_tres.v0_0_42_job_tres(
                    allocated = [
                        slurmrest_python.models.v0/0/42_tres.v0.0.42_tres(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, )
                        ], 
                    requested = [
                        slurmrest_python.models.v0/0/42_tres.v0.0.42_tres(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, )
                        ], ),
                used_gres = '',
                user = '',
                wckey = slurmrest_python.models.v0/0/42_wckey_tag_struct.v0.0.42_wckey_tag_struct(
                    wckey = '', 
                    flags = [
                        'ASSIGNED_DEFAULT'
                        ], ),
                working_directory = ''
            )
        else:
            return V0042Job(
        )
        """

    def testV0042Job(self):
        """Test V0042Job"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
