# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.2
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrest_python.models.v0042_job_info import V0042JobInfo

class TestV0042JobInfo(unittest.TestCase):
    """V0042JobInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0042JobInfo:
        """Test V0042JobInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0042JobInfo`
        """
        model = V0042JobInfo()
        if include_optional:
            return V0042JobInfo(
                account = '',
                accrue_time = slurmrest_python.models.v0/0/42_uint64_no_val_struct.v0.0.42_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                admin_comment = '',
                allocating_node = '',
                array_job_id = slurmrest_python.models.v0/0/42_uint32_no_val_struct.v0.0.42_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                array_task_id = slurmrest_python.models.v0/0/42_uint32_no_val_struct.v0.0.42_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                array_max_tasks = slurmrest_python.models.v0/0/42_uint32_no_val_struct.v0.0.42_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                array_task_string = '',
                association_id = 56,
                batch_features = '',
                batch_flag = True,
                batch_host = '',
                flags = [
                    'KILL_INVALID_DEPENDENCY'
                    ],
                burst_buffer = '',
                burst_buffer_state = '',
                cluster = '',
                cluster_features = '',
                command = '',
                comment = '',
                container = '',
                container_id = '',
                contiguous = True,
                core_spec = 56,
                thread_spec = 56,
                cores_per_socket = slurmrest_python.models.v0/0/42_uint16_no_val_struct.v0.0.42_uint16_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                billable_tres = slurmrest_python.models.v0/0/42_float64_no_val_struct.v0.0.42_float64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 1.337, ),
                cpus_per_task = slurmrest_python.models.v0/0/42_uint16_no_val_struct.v0.0.42_uint16_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                cpu_frequency_minimum = slurmrest_python.models.v0/0/42_uint32_no_val_struct.v0.0.42_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                cpu_frequency_maximum = slurmrest_python.models.v0/0/42_uint32_no_val_struct.v0.0.42_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                cpu_frequency_governor = slurmrest_python.models.v0/0/42_uint32_no_val_struct.v0.0.42_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                cpus_per_tres = '',
                cron = '',
                deadline = slurmrest_python.models.v0/0/42_uint64_no_val_struct.v0.0.42_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                delay_boot = slurmrest_python.models.v0/0/42_uint32_no_val_struct.v0.0.42_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                dependency = '',
                derived_exit_code = slurmrest_python.models.v0/0/42_process_exit_code_verbose.v0.0.42_process_exit_code_verbose(
                    status = [
                        'INVALID'
                        ], 
                    return_code = slurmrest_python.models.v0/0/42_uint32_no_val_struct.v0.0.42_uint32_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    signal = slurmrest_python.models.v0_0_42_process_exit_code_verbose_signal.v0_0_42_process_exit_code_verbose_signal(
                        id = slurmrest_python.models.v0/0/42_uint16_no_val_struct.v0.0.42_uint16_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        name = '', ), ),
                eligible_time = slurmrest_python.models.v0/0/42_uint64_no_val_struct.v0.0.42_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                end_time = slurmrest_python.models.v0/0/42_uint64_no_val_struct.v0.0.42_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                excluded_nodes = '',
                exit_code = slurmrest_python.models.v0/0/42_process_exit_code_verbose.v0.0.42_process_exit_code_verbose(
                    status = [
                        'INVALID'
                        ], 
                    return_code = slurmrest_python.models.v0/0/42_uint32_no_val_struct.v0.0.42_uint32_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    signal = slurmrest_python.models.v0_0_42_process_exit_code_verbose_signal.v0_0_42_process_exit_code_verbose_signal(
                        id = slurmrest_python.models.v0/0/42_uint16_no_val_struct.v0.0.42_uint16_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        name = '', ), ),
                extra = '',
                failed_node = '',
                features = '',
                federation_origin = '',
                federation_siblings_active = '',
                federation_siblings_viable = '',
                gres_detail = [
                    ''
                    ],
                group_id = 56,
                group_name = '',
                het_job_id = slurmrest_python.models.v0/0/42_uint32_no_val_struct.v0.0.42_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                het_job_id_set = '',
                het_job_offset = slurmrest_python.models.v0/0/42_uint32_no_val_struct.v0.0.42_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                job_id = 56,
                job_resources = slurmrest_python.models.v0/0/42_job_res.v0.0.42_job_res(
                    select_type = [
                        'CPU'
                        ], 
                    nodes = slurmrest_python.models.v0_0_42_job_res_nodes.v0_0_42_job_res_nodes(
                        count = 56, 
                        list = '', 
                        whole = True, 
                        allocation = [
                            slurmrest_python.models.v0/0/42_job_res_node.v0.0.42_job_res_node(
                                index = 56, 
                                name = '', 
                                cpus = slurmrest_python.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_cpus.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_cpus(
                                    count = 56, 
                                    used = 56, ), 
                                memory = slurmrest_python.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory(
                                    used = 56, 
                                    allocated = 56, ), 
                                sockets = [
                                    slurmrest_python.models.v0/0/42_job_res_socket.v0.0.42_job_res_socket(
                                        index = 56, 
                                        cores = [
                                            slurmrest_python.models.v0/0/42_job_res_core.v0.0.42_job_res_core(
                                                index = 56, 
                                                status = [
                                                    'INVALID'
                                                    ], )
                                            ], )
                                    ], )
                            ], ), 
                    cpus = 56, 
                    threads_per_core = slurmrest_python.models.v0/0/42_uint16_no_val_struct.v0.0.42_uint16_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), ),
                job_size_str = [
                    ''
                    ],
                job_state = [
                    'PENDING'
                    ],
                last_sched_evaluation = slurmrest_python.models.v0/0/42_uint64_no_val_struct.v0.0.42_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                licenses = '',
                mail_type = [
                    'BEGIN'
                    ],
                mail_user = '',
                max_cpus = slurmrest_python.models.v0/0/42_uint32_no_val_struct.v0.0.42_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                max_nodes = slurmrest_python.models.v0/0/42_uint32_no_val_struct.v0.0.42_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                mcs_label = '',
                memory_per_tres = '',
                name = '',
                network = '',
                nodes = '',
                nice = 56,
                tasks_per_core = slurmrest_python.models.v0/0/42_uint16_no_val_struct.v0.0.42_uint16_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                tasks_per_tres = slurmrest_python.models.v0/0/42_uint16_no_val_struct.v0.0.42_uint16_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                tasks_per_node = slurmrest_python.models.v0/0/42_uint16_no_val_struct.v0.0.42_uint16_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                tasks_per_socket = slurmrest_python.models.v0/0/42_uint16_no_val_struct.v0.0.42_uint16_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                tasks_per_board = slurmrest_python.models.v0/0/42_uint16_no_val_struct.v0.0.42_uint16_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                cpus = slurmrest_python.models.v0/0/42_uint32_no_val_struct.v0.0.42_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                node_count = slurmrest_python.models.v0/0/42_uint32_no_val_struct.v0.0.42_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                tasks = slurmrest_python.models.v0/0/42_uint32_no_val_struct.v0.0.42_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                partition = '',
                prefer = '',
                memory_per_cpu = slurmrest_python.models.v0/0/42_uint64_no_val_struct.v0.0.42_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                memory_per_node = slurmrest_python.models.v0/0/42_uint64_no_val_struct.v0.0.42_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                minimum_cpus_per_node = slurmrest_python.models.v0/0/42_uint16_no_val_struct.v0.0.42_uint16_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                minimum_tmp_disk_per_node = slurmrest_python.models.v0/0/42_uint32_no_val_struct.v0.0.42_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                power = slurmrest_python.models.v0_0_41_openapi_job_info_resp_jobs_inner_power.v0_0_41_openapi_job_info_resp_jobs_inner_power(
                    flags = [
                        null
                        ], ),
                preempt_time = slurmrest_python.models.v0/0/42_uint64_no_val_struct.v0.0.42_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                preemptable_time = slurmrest_python.models.v0/0/42_uint64_no_val_struct.v0.0.42_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                pre_sus_time = slurmrest_python.models.v0/0/42_uint64_no_val_struct.v0.0.42_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                hold = True,
                priority = slurmrest_python.models.v0/0/42_uint32_no_val_struct.v0.0.42_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                priority_by_partition = [
                    slurmrest_python.models.v0/0/42_part_prio.v0.0.42_part_prio(
                        partition = '', 
                        priority = 56, )
                    ],
                profile = [
                    'NOT_SET'
                    ],
                qos = '',
                reboot = True,
                required_nodes = '',
                required_switches = 56,
                requeue = True,
                resize_time = slurmrest_python.models.v0/0/42_uint64_no_val_struct.v0.0.42_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                restart_cnt = 56,
                resv_name = '',
                scheduled_nodes = '',
                selinux_context = '',
                shared = [
                    'none'
                    ],
                sockets_per_board = 56,
                sockets_per_node = slurmrest_python.models.v0/0/42_uint16_no_val_struct.v0.0.42_uint16_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                start_time = slurmrest_python.models.v0/0/42_uint64_no_val_struct.v0.0.42_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                state_description = '',
                state_reason = '',
                standard_error = '',
                standard_input = '',
                standard_output = '',
                submit_time = slurmrest_python.models.v0/0/42_uint64_no_val_struct.v0.0.42_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                suspend_time = slurmrest_python.models.v0/0/42_uint64_no_val_struct.v0.0.42_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                system_comment = '',
                time_limit = slurmrest_python.models.v0/0/42_uint32_no_val_struct.v0.0.42_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                time_minimum = slurmrest_python.models.v0/0/42_uint32_no_val_struct.v0.0.42_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                threads_per_core = slurmrest_python.models.v0/0/42_uint16_no_val_struct.v0.0.42_uint16_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                tres_bind = '',
                tres_freq = '',
                tres_per_job = '',
                tres_per_node = '',
                tres_per_socket = '',
                tres_per_task = '',
                tres_req_str = '',
                tres_alloc_str = '',
                user_id = 56,
                user_name = '',
                maximum_switch_wait_time = 56,
                wckey = '',
                current_working_directory = ''
            )
        else:
            return V0042JobInfo(
        )
        """

    def testV0042JobInfo(self):
        """Test V0042JobInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
