# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.2
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrest_python.models.v0043_assoc_max import V0043AssocMax

class TestV0043AssocMax(unittest.TestCase):
    """V0043AssocMax unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043AssocMax:
        """Test V0043AssocMax
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043AssocMax`
        """
        model = V0043AssocMax()
        if include_optional:
            return V0043AssocMax(
                jobs = slurmrest_python.models.v0_0_43_assoc_max_jobs.v0_0_43_assoc_max_jobs(
                    per = slurmrest_python.models.v0_0_43_assoc_max_jobs_per.v0_0_43_assoc_max_jobs_per(
                        count = slurmrest_python.models.v0/0/43_uint32_no_val_struct.v0.0.43_uint32_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        accruing = slurmrest_python.models.v0/0/43_uint32_no_val_struct.v0.0.43_uint32_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        submitted = , 
                        wall_clock = , ), 
                    active = , 
                    accruing = , 
                    total = , ),
                tres = slurmrest_python.models.v0_0_43_assoc_max_tres.v0_0_43_assoc_max_tres(
                    total = [
                        slurmrest_python.models.v0/0/43_tres.v0.0.43_tres(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, )
                        ], 
                    group = slurmrest_python.models.v0_0_43_assoc_max_tres_group.v0_0_43_assoc_max_tres_group(
                        minutes = [
                            slurmrest_python.models.v0/0/43_tres.v0.0.43_tres(
                                type = '', 
                                name = '', 
                                id = 56, 
                                count = 56, )
                            ], 
                        active = , ), 
                    minutes = slurmrest_python.models.v0_0_43_assoc_max_tres_minutes.v0_0_43_assoc_max_tres_minutes(
                        total = , 
                        per = slurmrest_python.models.v0_0_43_qos_limits_min_tres_per.v0_0_43_qos_limits_min_tres_per(
                            job = , ), ), 
                    per = slurmrest_python.models.v0_0_43_assoc_max_tres_per.v0_0_43_assoc_max_tres_per(
                        job = , 
                        node = , ), ),
                per = slurmrest_python.models.v0_0_43_assoc_max_per.v0_0_43_assoc_max_per(
                    account = slurmrest_python.models.v0_0_43_assoc_max_per_account.v0_0_43_assoc_max_per_account(
                        wall_clock = slurmrest_python.models.v0/0/43_uint32_no_val_struct.v0.0.43_uint32_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), ), )
            )
        else:
            return V0043AssocMax(
        )
        """

    def testV0043AssocMax(self):
        """Test V0043AssocMax"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
