# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.2
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrest_python.models.v0044_openapi_reservation_resp import V0044OpenapiReservationResp

class TestV0044OpenapiReservationResp(unittest.TestCase):
    """V0044OpenapiReservationResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0044OpenapiReservationResp:
        """Test V0044OpenapiReservationResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0044OpenapiReservationResp`
        """
        model = V0044OpenapiReservationResp()
        if include_optional:
            return V0044OpenapiReservationResp(
                reservations = [
                    slurmrest_python.models.v0/0/44_reservation_info.v0.0.44_reservation_info(
                        accounts = '', 
                        burst_buffer = '', 
                        core_count = 56, 
                        core_specializations = [
                            slurmrest_python.models.v0/0/44_reservation_core_spec.v0.0.44_reservation_core_spec(
                                node = '', 
                                core = '', )
                            ], 
                        end_time = slurmrest_python.models.v0/0/44_uint64_no_val_struct.v0.0.44_uint64_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        features = '', 
                        flags = [
                            'MAINT'
                            ], 
                        groups = '', 
                        licenses = '', 
                        max_start_delay = 56, 
                        name = '', 
                        node_count = 56, 
                        node_list = '', 
                        partition = '', 
                        purge_completed = slurmrest_python.models.v0_0_44_reservation_info_purge_completed.v0_0_44_reservation_info_purge_completed(
                            time = slurmrest_python.models.v0/0/44_uint32_no_val_struct.v0.0.44_uint32_no_val_struct(
                                set = True, 
                                infinite = True, 
                                number = 56, ), ), 
                        start_time = slurmrest_python.models.v0/0/44_uint64_no_val_struct.v0.0.44_uint64_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        watts = slurmrest_python.models.v0/0/44_uint32_no_val_struct.v0.0.44_uint32_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        tres = '', 
                        users = '', )
                    ],
                last_update = slurmrest_python.models.v0/0/44_uint64_no_val_struct.v0.0.44_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                meta = slurmrest_python.models.v0/0/44_openapi_meta.v0.0.44_openapi_meta(
                    plugin = slurmrest_python.models.v0_0_41_openapi_shares_resp_meta_plugin.v0_0_41_openapi_shares_resp_meta_plugin(
                        type = '', 
                        name = '', 
                        data_parser = '', 
                        accounting_storage = '', ), 
                    client = slurmrest_python.models.v0_0_41_openapi_shares_resp_meta_client.v0_0_41_openapi_shares_resp_meta_client(
                        source = '', 
                        user = '', 
                        group = '', ), 
                    command = [
                        ''
                        ], 
                    slurm = slurmrest_python.models.v0_0_41_openapi_shares_resp_meta_slurm.v0_0_41_openapi_shares_resp_meta_slurm(
                        version = slurmrest_python.models.v0_0_41_openapi_shares_resp_meta_slurm_version.v0_0_41_openapi_shares_resp_meta_slurm_version(
                            major = '', 
                            micro = '', 
                            minor = '', ), 
                        release = '', 
                        cluster = '', ), ),
                errors = [
                    slurmrest_python.models.v0/0/44_openapi_error.v0.0.44_openapi_error(
                        description = '', 
                        error_number = 56, 
                        error = '', 
                        source = '', )
                    ],
                warnings = [
                    slurmrest_python.models.v0/0/44_openapi_warning.v0.0.44_openapi_warning(
                        description = '', 
                        source = '', )
                    ]
            )
        else:
            return V0044OpenapiReservationResp(
                reservations = [
                    slurmrest_python.models.v0/0/44_reservation_info.v0.0.44_reservation_info(
                        accounts = '', 
                        burst_buffer = '', 
                        core_count = 56, 
                        core_specializations = [
                            slurmrest_python.models.v0/0/44_reservation_core_spec.v0.0.44_reservation_core_spec(
                                node = '', 
                                core = '', )
                            ], 
                        end_time = slurmrest_python.models.v0/0/44_uint64_no_val_struct.v0.0.44_uint64_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        features = '', 
                        flags = [
                            'MAINT'
                            ], 
                        groups = '', 
                        licenses = '', 
                        max_start_delay = 56, 
                        name = '', 
                        node_count = 56, 
                        node_list = '', 
                        partition = '', 
                        purge_completed = slurmrest_python.models.v0_0_44_reservation_info_purge_completed.v0_0_44_reservation_info_purge_completed(
                            time = slurmrest_python.models.v0/0/44_uint32_no_val_struct.v0.0.44_uint32_no_val_struct(
                                set = True, 
                                infinite = True, 
                                number = 56, ), ), 
                        start_time = slurmrest_python.models.v0/0/44_uint64_no_val_struct.v0.0.44_uint64_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        watts = slurmrest_python.models.v0/0/44_uint32_no_val_struct.v0.0.44_uint32_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        tres = '', 
                        users = '', )
                    ],
                last_update = slurmrest_python.models.v0/0/44_uint64_no_val_struct.v0.0.44_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
        )
        """

    def testV0044OpenapiReservationResp(self):
        """Test V0044OpenapiReservationResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
