# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.2
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrest_python.models.v0043_openapi_licenses_resp import V0043OpenapiLicensesResp

class TestV0043OpenapiLicensesResp(unittest.TestCase):
    """V0043OpenapiLicensesResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043OpenapiLicensesResp:
        """Test V0043OpenapiLicensesResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043OpenapiLicensesResp`
        """
        model = V0043OpenapiLicensesResp()
        if include_optional:
            return V0043OpenapiLicensesResp(
                licenses = [
                    slurmrest_python.models.v0/0/43_license.v0.0.43_license(
                        license_name = '', 
                        total = 56, 
                        used = 56, 
                        free = 56, 
                        remote = True, 
                        reserved = 56, 
                        last_consumed = 56, 
                        last_deficit = 56, 
                        last_update = 56, )
                    ],
                last_update = slurmrest_python.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                meta = slurmrest_python.models.v0/0/43_openapi_meta.v0.0.43_openapi_meta(
                    plugin = slurmrest_python.models.v0_0_41_openapi_shares_resp_meta_plugin.v0_0_41_openapi_shares_resp_meta_plugin(
                        type = '', 
                        name = '', 
                        data_parser = '', 
                        accounting_storage = '', ), 
                    client = slurmrest_python.models.v0_0_41_openapi_shares_resp_meta_client.v0_0_41_openapi_shares_resp_meta_client(
                        source = '', 
                        user = '', 
                        group = '', ), 
                    command = [
                        ''
                        ], 
                    slurm = slurmrest_python.models.v0_0_41_openapi_shares_resp_meta_slurm.v0_0_41_openapi_shares_resp_meta_slurm(
                        version = slurmrest_python.models.v0_0_41_openapi_shares_resp_meta_slurm_version.v0_0_41_openapi_shares_resp_meta_slurm_version(
                            major = '', 
                            micro = '', 
                            minor = '', ), 
                        release = '', 
                        cluster = '', ), ),
                errors = [
                    slurmrest_python.models.v0/0/43_openapi_error.v0.0.43_openapi_error(
                        description = '', 
                        error_number = 56, 
                        error = '', 
                        source = '', )
                    ],
                warnings = [
                    slurmrest_python.models.v0/0/43_openapi_warning.v0.0.43_openapi_warning(
                        description = '', 
                        source = '', )
                    ]
            )
        else:
            return V0043OpenapiLicensesResp(
                licenses = [
                    slurmrest_python.models.v0/0/43_license.v0.0.43_license(
                        license_name = '', 
                        total = 56, 
                        used = 56, 
                        free = 56, 
                        remote = True, 
                        reserved = 56, 
                        last_consumed = 56, 
                        last_deficit = 56, 
                        last_update = 56, )
                    ],
                last_update = slurmrest_python.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
        )
        """

    def testV0043OpenapiLicensesResp(self):
        """Test V0043OpenapiLicensesResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
