# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.2
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrest_python.models.v0044_assoc_max_tres import V0044AssocMaxTres

class TestV0044AssocMaxTres(unittest.TestCase):
    """V0044AssocMaxTres unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0044AssocMaxTres:
        """Test V0044AssocMaxTres
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0044AssocMaxTres`
        """
        model = V0044AssocMaxTres()
        if include_optional:
            return V0044AssocMaxTres(
                total = [
                    slurmrest_python.models.v0/0/44_tres.v0.0.44_tres(
                        type = '', 
                        name = '', 
                        id = 56, 
                        count = 56, )
                    ],
                group = slurmrest_python.models.v0_0_44_assoc_max_tres_group.v0_0_44_assoc_max_tres_group(
                    minutes = [
                        slurmrest_python.models.v0/0/44_tres.v0.0.44_tres(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, )
                        ], 
                    active = [
                        slurmrest_python.models.v0/0/44_tres.v0.0.44_tres(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, )
                        ], ),
                minutes = slurmrest_python.models.v0_0_44_assoc_max_tres_minutes.v0_0_44_assoc_max_tres_minutes(
                    total = [
                        slurmrest_python.models.v0/0/44_tres.v0.0.44_tres(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, )
                        ], 
                    per = slurmrest_python.models.v0_0_44_qos_limits_min_tres_per.v0_0_44_qos_limits_min_tres_per(
                        job = [
                            slurmrest_python.models.v0/0/44_tres.v0.0.44_tres(
                                type = '', 
                                name = '', 
                                id = 56, 
                                count = 56, )
                            ], ), ),
                per = slurmrest_python.models.v0_0_44_assoc_max_tres_per.v0_0_44_assoc_max_tres_per(
                    job = [
                        slurmrest_python.models.v0/0/44_tres.v0.0.44_tres(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, )
                        ], 
                    node = [
                        slurmrest_python.models.v0/0/44_tres.v0.0.44_tres(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, )
                        ], )
            )
        else:
            return V0044AssocMaxTres(
        )
        """

    def testV0044AssocMaxTres(self):
        """Test V0044AssocMaxTres"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
