# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.2
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrest_python.models.v0041_openapi_slurmdbd_config_resp import V0041OpenapiSlurmdbdConfigResp

class TestV0041OpenapiSlurmdbdConfigResp(unittest.TestCase):
    """V0041OpenapiSlurmdbdConfigResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiSlurmdbdConfigResp:
        """Test V0041OpenapiSlurmdbdConfigResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiSlurmdbdConfigResp`
        """
        model = V0041OpenapiSlurmdbdConfigResp()
        if include_optional:
            return V0041OpenapiSlurmdbdConfigResp(
                clusters = [
                    slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_clusters_inner.v0_0_41_openapi_slurmdbd_config_resp_clusters_inner(
                        controller = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_clusters_inner_controller.v0_0_41_openapi_slurmdbd_config_resp_clusters_inner_controller(
                            host = '', 
                            port = 56, ), 
                        flags = [
                            'REGISTERING'
                            ], 
                        name = '', 
                        nodes = '', 
                        select_plugin = '', 
                        associations = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_clusters_inner_associations.v0_0_41_openapi_slurmdbd_config_resp_clusters_inner_associations(
                            root = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_clusters_inner_associations_root.v0_0_41_openapi_slurmdbd_config_resp_clusters_inner_associations_root(
                                account = '', 
                                cluster = '', 
                                partition = '', 
                                user = '', 
                                id = 56, ), ), 
                        rpc_version = 56, 
                        tres = [
                            slurmrest_python.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner(
                                type = '', 
                                name = '', 
                                id = 56, 
                                count = 56, )
                            ], )
                    ],
                tres = [
                    slurmrest_python.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner(
                        type = '', 
                        name = '', 
                        id = 56, 
                        count = 56, )
                    ],
                accounts = [
                    slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_accounts_inner.v0_0_41_openapi_slurmdbd_config_resp_accounts_inner(
                        associations = [
                            slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_accounts_inner_associations_inner.v0_0_41_openapi_slurmdbd_config_resp_accounts_inner_associations_inner(
                                account = '', 
                                cluster = '', 
                                partition = '', 
                                user = '', 
                                id = 56, )
                            ], 
                        coordinators = [
                            slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_accounts_inner_coordinators_inner.v0_0_41_openapi_slurmdbd_config_resp_accounts_inner_coordinators_inner(
                                name = '', 
                                direct = True, )
                            ], 
                        description = '', 
                        name = '', 
                        organization = '', 
                        flags = [
                            'DELETED'
                            ], )
                    ],
                users = [
                    slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_users_inner.v0_0_41_openapi_slurmdbd_config_resp_users_inner(
                        administrator_level = [
                            'Not Set'
                            ], 
                        associations = [
                            slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_accounts_inner_associations_inner.v0_0_41_openapi_slurmdbd_config_resp_accounts_inner_associations_inner(
                                account = '', 
                                cluster = '', 
                                partition = '', 
                                user = '', 
                                id = 56, )
                            ], 
                        coordinators = [
                            slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_accounts_inner_coordinators_inner.v0_0_41_openapi_slurmdbd_config_resp_accounts_inner_coordinators_inner(
                                name = '', 
                                direct = True, )
                            ], 
                        default = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_users_inner_default.v0_0_41_openapi_slurmdbd_config_resp_users_inner_default(
                            account = '', 
                            wckey = '', ), 
                        flags = [
                            'NONE'
                            ], 
                        name = '', 
                        old_name = '', 
                        wckeys = [
                            slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_users_inner_wckeys_inner.v0_0_41_openapi_slurmdbd_config_resp_users_inner_wckeys_inner(
                                accounting = [
                                    slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_users_inner_wckeys_inner_accounting_inner.v0_0_41_openapi_slurmdbd_config_resp_users_inner_wckeys_inner_accounting_inner(
                                        allocated = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_users_inner_wckeys_inner_accounting_inner_allocated.v0_0_41_openapi_slurmdbd_config_resp_users_inner_wckeys_inner_accounting_inner_allocated(
                                            seconds = 56, ), 
                                        id = 56, 
                                        start = 56, 
                                        tres = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_users_inner_wckeys_inner_accounting_inner_tres.v0_0_41_openapi_slurmdbd_config_resp_users_inner_wckeys_inner_accounting_inner_TRES(
                                            type = '', 
                                            name = '', 
                                            id = 56, 
                                            count = 56, ), )
                                    ], 
                                cluster = '', 
                                id = 56, 
                                name = '', 
                                user = '', )
                            ], )
                    ],
                qos = [
                    slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner.v0_0_41_openapi_slurmdbd_config_resp_qos_inner(
                        description = '', 
                        flags = [
                            'NOT_SET'
                            ], 
                        id = 56, 
                        limits = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits(
                            grace_time = 56, 
                            max = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max(
                                active_jobs = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_active_jobs.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_active_jobs(
                                    accruing = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_active_jobs_accruing.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_active_jobs_accruing(
                                        set = True, 
                                        infinite = True, 
                                        number = 56, ), 
                                    count = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_active_jobs_count.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_active_jobs_count(
                                        set = True, 
                                        infinite = True, 
                                        number = 56, ), ), 
                                tres = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_tres.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_tres(
                                    total = [
                                        slurmrest_python.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner(
                                            type = '', 
                                            name = '', 
                                            id = 56, )
                                        ], 
                                    minutes = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_tres_minutes.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_tres_minutes(
                                        per = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_tres_minutes_per.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_tres_minutes_per(
                                            qos = [
                                                slurmrest_python.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner(
                                                    type = '', 
                                                    name = '', 
                                                    id = 56, )
                                                ], 
                                            job = [
                                                
                                                ], 
                                            account = [
                                                
                                                ], 
                                            user = [
                                                
                                                ], ), ), 
                                    per = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_tres_per.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_tres_per(
                                        node = [
                                            
                                            ], ), ), 
                                wall_clock = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_wall_clock.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_wall_clock(), 
                                jobs = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_jobs.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_jobs(), 
                                accruing = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing(), ), 
                            factor = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_factor.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_factor(
                                set = True, 
                                infinite = True, 
                                number = 1.337, ), 
                            min = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_min.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_min(
                                priority_threshold = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_min_priority_threshold.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_min_priority_threshold(
                                    set = True, 
                                    infinite = True, 
                                    number = 56, ), ), ), 
                        name = '', 
                        preempt = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_preempt.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_preempt(
                            list = [
                                ''
                                ], 
                            mode = [
                                'DISABLED'
                                ], 
                            exempt_time = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_preempt_exempt_time.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_preempt_exempt_time(
                                set = True, 
                                infinite = True, 
                                number = 56, ), ), 
                        priority = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_priority.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_priority(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        usage_factor = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_usage_factor.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_usage_factor(
                            set = True, 
                            infinite = True, 
                            number = 1.337, ), 
                        usage_threshold = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_usage_threshold.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_usage_threshold(
                            set = True, 
                            infinite = True, 
                            number = 1.337, ), )
                    ],
                wckeys = [
                    slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_users_inner_wckeys_inner.v0_0_41_openapi_slurmdbd_config_resp_users_inner_wckeys_inner(
                        accounting = [
                            slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_users_inner_wckeys_inner_accounting_inner.v0_0_41_openapi_slurmdbd_config_resp_users_inner_wckeys_inner_accounting_inner(
                                allocated = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_users_inner_wckeys_inner_accounting_inner_allocated.v0_0_41_openapi_slurmdbd_config_resp_users_inner_wckeys_inner_accounting_inner_allocated(
                                    seconds = 56, ), 
                                id = 56, 
                                start = 56, 
                                tres = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_users_inner_wckeys_inner_accounting_inner_tres.v0_0_41_openapi_slurmdbd_config_resp_users_inner_wckeys_inner_accounting_inner_TRES(
                                    type = '', 
                                    name = '', 
                                    id = 56, 
                                    count = 56, ), )
                            ], 
                        cluster = '', 
                        id = 56, 
                        name = '', 
                        user = '', 
                        flags = [
                            'DELETED'
                            ], )
                    ],
                associations = [
                    slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_associations_inner.v0_0_41_openapi_slurmdbd_config_resp_associations_inner(
                        accounting = [
                            slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_users_inner_wckeys_inner_accounting_inner.v0_0_41_openapi_slurmdbd_config_resp_users_inner_wckeys_inner_accounting_inner(
                                allocated = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_users_inner_wckeys_inner_accounting_inner_allocated.v0_0_41_openapi_slurmdbd_config_resp_users_inner_wckeys_inner_accounting_inner_allocated(
                                    seconds = 56, ), 
                                id = 56, 
                                start = 56, 
                                tres = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_users_inner_wckeys_inner_accounting_inner_tres.v0_0_41_openapi_slurmdbd_config_resp_users_inner_wckeys_inner_accounting_inner_TRES(
                                    type = '', 
                                    name = '', 
                                    id = 56, 
                                    count = 56, ), )
                            ], 
                        account = '', 
                        cluster = '', 
                        comment = '', 
                        default = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_default.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_default(
                            qos = '', ), 
                        flags = [
                            'DELETED'
                            ], 
                        max = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max(
                            jobs = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_jobs.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_jobs(
                                per = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_jobs_per.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_jobs_per(
                                    count = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_active_jobs_count.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_active_jobs_count(
                                        set = True, 
                                        infinite = True, 
                                        number = 56, ), 
                                    accruing = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_active_jobs_accruing.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_active_jobs_accruing(
                                        set = True, 
                                        infinite = True, 
                                        number = 56, ), 
                                    submitted = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_jobs_per_submitted.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_jobs_per_submitted(
                                        set = True, 
                                        infinite = True, 
                                        number = 56, ), 
                                    wall_clock = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_wall_clock_per_job.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_wall_clock_per_job(
                                        set = True, 
                                        infinite = True, 
                                        number = 56, ), ), 
                                active = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_jobs_active.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_jobs_active(
                                    set = True, 
                                    infinite = True, 
                                    number = 56, ), 
                                accruing = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_jobs_accruing.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_jobs_accruing(
                                    set = True, 
                                    infinite = True, 
                                    number = 56, ), 
                                total = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_jobs_total.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_jobs_total(
                                    set = True, 
                                    infinite = True, 
                                    number = 56, ), ), 
                            tres = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_tres.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_tres(
                                group = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_tres_group.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_tres_group(
                                    minutes = [
                                        slurmrest_python.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner(
                                            type = '', 
                                            name = '', 
                                            id = 56, )
                                        ], ), 
                                minutes = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_tres_minutes.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_tres_minutes(), ), 
                            per = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_per.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_per(
                                account = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_per_account.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_per_account(), ), ), 
                        id = 56, 
                        is_default = True, 
                        lineage = '', 
                        min = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_min.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_min(
                            priority_threshold = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_min_priority_threshold.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_min_priority_threshold(
                                set = True, 
                                infinite = True, 
                                number = 56, ), ), 
                        parent_account = '', 
                        partition = '', 
                        priority = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_priority.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_priority(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        qos = [
                            ''
                            ], 
                        shares_raw = 56, 
                        user = '', )
                    ],
                instances = [
                    slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_instances_inner.v0_0_41_openapi_slurmdbd_config_resp_instances_inner(
                        cluster = '', 
                        extra = '', 
                        instance_id = '', 
                        instance_type = '', 
                        node_name = '', 
                        time = slurmrest_python.models.v0_0_41_openapi_slurmdbd_config_resp_instances_inner_time.v0_0_41_openapi_slurmdbd_config_resp_instances_inner_time(
                            time_end = 56, 
                            time_start = 56, ), )
                    ],
                meta = slurmrest_python.models.v0_0_41_openapi_shares_resp_meta.v0_0_41_openapi_shares_resp_meta(
                    plugin = slurmrest_python.models.v0_0_41_openapi_shares_resp_meta_plugin.v0_0_41_openapi_shares_resp_meta_plugin(
                        type = '', 
                        name = '', 
                        data_parser = '', 
                        accounting_storage = '', ), 
                    client = slurmrest_python.models.v0_0_41_openapi_shares_resp_meta_client.v0_0_41_openapi_shares_resp_meta_client(
                        source = '', 
                        user = '', 
                        group = '', ), 
                    command = [
                        ''
                        ], 
                    slurm = slurmrest_python.models.v0_0_41_openapi_shares_resp_meta_slurm.v0_0_41_openapi_shares_resp_meta_slurm(
                        version = slurmrest_python.models.v0_0_41_openapi_shares_resp_meta_slurm_version.v0_0_41_openapi_shares_resp_meta_slurm_version(
                            major = '', 
                            micro = '', 
                            minor = '', ), 
                        release = '', 
                        cluster = '', ), ),
                errors = [
                    slurmrest_python.models.v0_0_41_openapi_shares_resp_errors_inner.v0_0_41_openapi_shares_resp_errors_inner(
                        description = '', 
                        error_number = 56, 
                        error = '', 
                        source = '', )
                    ],
                warnings = [
                    slurmrest_python.models.v0_0_41_openapi_shares_resp_warnings_inner.v0_0_41_openapi_shares_resp_warnings_inner(
                        description = '', 
                        source = '', )
                    ]
            )
        else:
            return V0041OpenapiSlurmdbdConfigResp(
        )
        """

    def testV0041OpenapiSlurmdbdConfigResp(self):
        """Test V0041OpenapiSlurmdbdConfigResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
