# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.2
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrest_python.models.v0042_openapi_slurmdbd_stats_resp import V0042OpenapiSlurmdbdStatsResp

class TestV0042OpenapiSlurmdbdStatsResp(unittest.TestCase):
    """V0042OpenapiSlurmdbdStatsResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0042OpenapiSlurmdbdStatsResp:
        """Test V0042OpenapiSlurmdbdStatsResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0042OpenapiSlurmdbdStatsResp`
        """
        model = V0042OpenapiSlurmdbdStatsResp()
        if include_optional:
            return V0042OpenapiSlurmdbdStatsResp(
                statistics = slurmrest_python.models.v0/0/42_stats_rec.v0.0.42_stats_rec(
                    time_start = 56, 
                    rollups = slurmrest_python.models.v0/0/42_rollup_stats.v0.0.42_rollup_stats(
                        hourly = slurmrest_python.models.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_hourly.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_hourly(
                            count = 56, 
                            last_run = 56, 
                            duration = slurmrest_python.models.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_hourly_duration.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_hourly_duration(
                                last = 56, 
                                max = 56, 
                                time = 56, ), ), 
                        daily = slurmrest_python.models.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_daily.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_daily(
                            count = 56, 
                            last_run = 56, ), 
                        monthly = slurmrest_python.models.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_monthly.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_monthly(
                            count = 56, 
                            last_run = 56, ), ), 
                    rpcs = [
                        slurmrest_python.models.v0/0/42_stats_rpc.v0.0.42_stats_rpc(
                            rpc = '', 
                            count = 56, 
                            time = slurmrest_python.models.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rpcs_inner_time.v0_0_41_openapi_slurmdbd_stats_resp_statistics_RPCs_inner_time(
                                average = 56, 
                                total = 56, ), )
                        ], 
                    users = [
                        slurmrest_python.models.v0/0/42_stats_user.v0.0.42_stats_user(
                            user = '', 
                            count = 56, )
                        ], ),
                meta = slurmrest_python.models.v0/0/42_openapi_meta.v0.0.42_openapi_meta(
                    plugin = slurmrest_python.models.v0_0_41_openapi_shares_resp_meta_plugin.v0_0_41_openapi_shares_resp_meta_plugin(
                        type = '', 
                        name = '', 
                        data_parser = '', 
                        accounting_storage = '', ), 
                    client = slurmrest_python.models.v0_0_41_openapi_shares_resp_meta_client.v0_0_41_openapi_shares_resp_meta_client(
                        source = '', 
                        user = '', 
                        group = '', ), 
                    command = [
                        ''
                        ], 
                    slurm = slurmrest_python.models.v0_0_41_openapi_shares_resp_meta_slurm.v0_0_41_openapi_shares_resp_meta_slurm(
                        version = slurmrest_python.models.v0_0_41_openapi_shares_resp_meta_slurm_version.v0_0_41_openapi_shares_resp_meta_slurm_version(
                            major = '', 
                            micro = '', 
                            minor = '', ), 
                        release = '', 
                        cluster = '', ), ),
                errors = [
                    slurmrest_python.models.v0/0/42_openapi_error.v0.0.42_openapi_error(
                        description = '', 
                        error_number = 56, 
                        error = '', 
                        source = '', )
                    ],
                warnings = [
                    slurmrest_python.models.v0/0/42_openapi_warning.v0.0.42_openapi_warning(
                        description = '', 
                        source = '', )
                    ]
            )
        else:
            return V0042OpenapiSlurmdbdStatsResp(
                statistics = slurmrest_python.models.v0/0/42_stats_rec.v0.0.42_stats_rec(
                    time_start = 56, 
                    rollups = slurmrest_python.models.v0/0/42_rollup_stats.v0.0.42_rollup_stats(
                        hourly = slurmrest_python.models.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_hourly.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_hourly(
                            count = 56, 
                            last_run = 56, 
                            duration = slurmrest_python.models.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_hourly_duration.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_hourly_duration(
                                last = 56, 
                                max = 56, 
                                time = 56, ), ), 
                        daily = slurmrest_python.models.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_daily.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_daily(
                            count = 56, 
                            last_run = 56, ), 
                        monthly = slurmrest_python.models.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_monthly.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_monthly(
                            count = 56, 
                            last_run = 56, ), ), 
                    rpcs = [
                        slurmrest_python.models.v0/0/42_stats_rpc.v0.0.42_stats_rpc(
                            rpc = '', 
                            count = 56, 
                            time = slurmrest_python.models.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rpcs_inner_time.v0_0_41_openapi_slurmdbd_stats_resp_statistics_RPCs_inner_time(
                                average = 56, 
                                total = 56, ), )
                        ], 
                    users = [
                        slurmrest_python.models.v0/0/42_stats_user.v0.0.42_stats_user(
                            user = '', 
                            count = 56, )
                        ], ),
        )
        """

    def testV0042OpenapiSlurmdbdStatsResp(self):
        """Test V0042OpenapiSlurmdbdStatsResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
