# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.2
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrest_python.models.v0044_job_desc_msg_rlimits import V0044JobDescMsgRlimits

class TestV0044JobDescMsgRlimits(unittest.TestCase):
    """V0044JobDescMsgRlimits unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0044JobDescMsgRlimits:
        """Test V0044JobDescMsgRlimits
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0044JobDescMsgRlimits`
        """
        model = V0044JobDescMsgRlimits()
        if include_optional:
            return V0044JobDescMsgRlimits(
                cpu = slurmrest_python.models.v0/0/44_uint64_no_val_struct.v0.0.44_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                fsize = slurmrest_python.models.v0/0/44_uint64_no_val_struct.v0.0.44_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                data = slurmrest_python.models.v0/0/44_uint64_no_val_struct.v0.0.44_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                stack = slurmrest_python.models.v0/0/44_uint64_no_val_struct.v0.0.44_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                core = slurmrest_python.models.v0/0/44_uint64_no_val_struct.v0.0.44_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                rss = slurmrest_python.models.v0/0/44_uint64_no_val_struct.v0.0.44_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                nproc = slurmrest_python.models.v0/0/44_uint64_no_val_struct.v0.0.44_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                nofile = slurmrest_python.models.v0/0/44_uint64_no_val_struct.v0.0.44_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                memlock = slurmrest_python.models.v0/0/44_uint64_no_val_struct.v0.0.44_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                var_as = slurmrest_python.models.v0/0/44_uint64_no_val_struct.v0.0.44_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, )
            )
        else:
            return V0044JobDescMsgRlimits(
        )
        """

    def testV0044JobDescMsgRlimits(self):
        """Test V0044JobDescMsgRlimits"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
