# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.2
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrest_python.models.v0044_qos_limits_max import V0044QosLimitsMax

class TestV0044QosLimitsMax(unittest.TestCase):
    """V0044QosLimitsMax unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0044QosLimitsMax:
        """Test V0044QosLimitsMax
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0044QosLimitsMax`
        """
        model = V0044QosLimitsMax()
        if include_optional:
            return V0044QosLimitsMax(
                active_jobs = slurmrest_python.models.v0_0_44_qos_limits_max_active_jobs.v0_0_44_qos_limits_max_active_jobs(
                    accruing = slurmrest_python.models.v0/0/44_uint32_no_val_struct.v0.0.44_uint32_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    count = slurmrest_python.models.v0/0/44_uint32_no_val_struct.v0.0.44_uint32_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), ),
                jobs = slurmrest_python.models.v0_0_44_qos_limits_max_jobs.v0_0_44_qos_limits_max_jobs(
                    count = slurmrest_python.models.v0/0/44_uint32_no_val_struct.v0.0.44_uint32_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    active_jobs = slurmrest_python.models.v0_0_44_qos_limits_max_jobs_active_jobs.v0_0_44_qos_limits_max_jobs_active_jobs(
                        per = slurmrest_python.models.v0_0_44_qos_limits_max_jobs_active_jobs_per.v0_0_44_qos_limits_max_jobs_active_jobs_per(
                            account = slurmrest_python.models.v0/0/44_uint32_no_val_struct.v0.0.44_uint32_no_val_struct(
                                set = True, 
                                infinite = True, 
                                number = 56, ), 
                            user = , ), ), 
                    per = slurmrest_python.models.v0_0_44_qos_limits_max_jobs_active_jobs_per.v0_0_44_qos_limits_max_jobs_active_jobs_per(), ),
                tres = slurmrest_python.models.v0_0_44_qos_limits_max_tres.v0_0_44_qos_limits_max_tres(
                    total = [
                        slurmrest_python.models.v0/0/44_tres.v0.0.44_tres(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, )
                        ], 
                    minutes = slurmrest_python.models.v0_0_44_qos_limits_max_tres_minutes.v0_0_44_qos_limits_max_tres_minutes(
                        total = [
                            slurmrest_python.models.v0/0/44_tres.v0.0.44_tres(
                                type = '', 
                                name = '', 
                                id = 56, 
                                count = 56, )
                            ], 
                        per = slurmrest_python.models.v0_0_44_qos_limits_max_tres_minutes_per.v0_0_44_qos_limits_max_tres_minutes_per(
                            qos = , 
                            job = , 
                            account = , 
                            user = , ), ), 
                    per = slurmrest_python.models.v0_0_44_qos_limits_max_tres_per.v0_0_44_qos_limits_max_tres_per(
                        account = , 
                        job = , 
                        node = , 
                        user = , ), ),
                wall_clock = slurmrest_python.models.v0_0_44_qos_limits_max_wall_clock.v0_0_44_qos_limits_max_wall_clock(
                    per = slurmrest_python.models.v0_0_44_qos_limits_max_wall_clock_per.v0_0_44_qos_limits_max_wall_clock_per(
                        qos = slurmrest_python.models.v0/0/44_uint32_no_val_struct.v0.0.44_uint32_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        job = slurmrest_python.models.v0/0/44_uint32_no_val_struct.v0.0.44_uint32_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), ), ),
                accruing = slurmrest_python.models.v0_0_44_qos_limits_max_jobs_active_jobs.v0_0_44_qos_limits_max_jobs_active_jobs(
                    per = slurmrest_python.models.v0_0_44_qos_limits_max_jobs_active_jobs_per.v0_0_44_qos_limits_max_jobs_active_jobs_per(
                        account = slurmrest_python.models.v0/0/44_uint32_no_val_struct.v0.0.44_uint32_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        user = slurmrest_python.models.v0/0/44_uint32_no_val_struct.v0.0.44_uint32_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), ), )
            )
        else:
            return V0044QosLimitsMax(
        )
        """

    def testV0044QosLimitsMax(self):
        """Test V0044QosLimitsMax"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
