# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.2
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrest_python.models.v0044_partition_info import V0044PartitionInfo

class TestV0044PartitionInfo(unittest.TestCase):
    """V0044PartitionInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0044PartitionInfo:
        """Test V0044PartitionInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0044PartitionInfo`
        """
        model = V0044PartitionInfo()
        if include_optional:
            return V0044PartitionInfo(
                nodes = slurmrest_python.models.v0_0_44_partition_info_nodes.v0_0_44_partition_info_nodes(
                    allowed_allocation = '', 
                    configured = '', 
                    total = 56, ),
                accounts = slurmrest_python.models.v0_0_44_partition_info_accounts.v0_0_44_partition_info_accounts(
                    allowed = '', 
                    deny = '', ),
                groups = slurmrest_python.models.v0_0_44_partition_info_groups.v0_0_44_partition_info_groups(
                    allowed = '', ),
                qos = slurmrest_python.models.v0_0_44_partition_info_qos.v0_0_44_partition_info_qos(
                    allowed = '', 
                    deny = '', 
                    assigned = '', ),
                alternate = '',
                tres = slurmrest_python.models.v0_0_44_partition_info_tres.v0_0_44_partition_info_tres(
                    billing_weights = '', 
                    configured = '', ),
                cluster = '',
                select_type = [
                    'CPU'
                    ],
                cpus = slurmrest_python.models.v0_0_44_partition_info_cpus.v0_0_44_partition_info_cpus(
                    task_binding = 56, 
                    total = 56, ),
                defaults = slurmrest_python.models.v0_0_44_partition_info_defaults.v0_0_44_partition_info_defaults(
                    memory_per_cpu = 56, 
                    partition_memory_per_cpu = slurmrest_python.models.v0/0/44_uint64_no_val_struct.v0.0.44_uint64_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    partition_memory_per_node = slurmrest_python.models.v0/0/44_uint64_no_val_struct.v0.0.44_uint64_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    time = slurmrest_python.models.v0/0/44_uint32_no_val_struct.v0.0.44_uint32_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    job = '', ),
                grace_time = 56,
                maximums = slurmrest_python.models.v0_0_44_partition_info_maximums.v0_0_44_partition_info_maximums(
                    cpus_per_node = slurmrest_python.models.v0/0/44_uint32_no_val_struct.v0.0.44_uint32_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    cpus_per_socket = slurmrest_python.models.v0/0/44_uint32_no_val_struct.v0.0.44_uint32_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    memory_per_cpu = 56, 
                    partition_memory_per_cpu = slurmrest_python.models.v0/0/44_uint64_no_val_struct.v0.0.44_uint64_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    partition_memory_per_node = slurmrest_python.models.v0/0/44_uint64_no_val_struct.v0.0.44_uint64_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    nodes = , 
                    shares = 56, 
                    oversubscribe = slurmrest_python.models.v0_0_41_openapi_partition_resp_partitions_inner_maximums_oversubscribe.v0_0_41_openapi_partition_resp_partitions_inner_maximums_oversubscribe(
                        jobs = 56, 
                        flags = [
                            'force'
                            ], ), 
                    time = , 
                    over_time_limit = slurmrest_python.models.v0/0/44_uint16_no_val_struct.v0.0.44_uint16_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), ),
                minimums = slurmrest_python.models.v0_0_44_partition_info_minimums.v0_0_44_partition_info_minimums(
                    nodes = 56, ),
                name = '',
                node_sets = '',
                priority = slurmrest_python.models.v0_0_44_partition_info_priority.v0_0_44_partition_info_priority(
                    job_factor = 56, 
                    tier = 56, ),
                timeouts = slurmrest_python.models.v0_0_44_partition_info_timeouts.v0_0_44_partition_info_timeouts(
                    resume = slurmrest_python.models.v0/0/44_uint16_no_val_struct.v0.0.44_uint16_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    suspend = slurmrest_python.models.v0/0/44_uint16_no_val_struct.v0.0.44_uint16_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), ),
                topology = '',
                partition = slurmrest_python.models.v0_0_41_openapi_partition_resp_partitions_inner_partition.v0_0_41_openapi_partition_resp_partitions_inner_partition(
                    state = [
                        'INACTIVE'
                        ], ),
                suspend_time = slurmrest_python.models.v0/0/44_uint32_no_val_struct.v0.0.44_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, )
            )
        else:
            return V0044PartitionInfo(
        )
        """

    def testV0044PartitionInfo(self):
        """Test V0044PartitionInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
